config/routes.rb
Rails.application.routes.draw do

  # PUBLIC ROUTES

  mount Attachinary::Engine => "/attachinary"

   root to: 'pages#home'

   # get '/instahome' => 'pages#instahome'
  # gem high voltage to use a helper method for static pages

  get '/contact' => 'pages#contact'

  get '/home' => 'pages#home'

  get '/about' => 'pages#about'
  get '/press' => 'pages#press'

  get '/collection' => 'products#index'


  resources :products, only: [:show]

  resources :scenes, only: [:show]

  # ADMIN ROUTES


  get '/admin' => 'admin/dashboards#show' # I added this route because I kept typing it.

  devise_for :users

  namespace :admin do

    resources :scenes do
      member do
        delete :remove_product
        post :add_product
      end
    end

    resources :products
    resource :dashboard, only: [:show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin_products_controller.rb
class AdminProductsController < ApplicationController
  layout 'admin_layout'
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.new
  end

  def create
   @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product)
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def show
    # @product = Product.find(params[:id])
  end

  def edit
    # @product = Product.find(params[:id])
  end

  def update
    # @product = product.find(params[:id])
    @product.update(product_params)
    redirect_to admin_product_path(@product)
  end

  def destroy
    # @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path
  end

private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :photo, :photo_cache)
  end

end

app/helpers/admin_products_helper.rb
module AdminProductsHelper
end

app/views/admin_products/index.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Products
        </h1>
        <ol class="breadcrumb">
          <li>
            <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
          </li>
          <li class="active">
            <i class="fa fa-desktop"></i> Products
          </li>
        </ol>
      </div>
    </div>


    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
    <div>
      <table class="table table-striped table-hover">
        <p><a href="/admin_products/new" class="btn btn-primary" role="button"> Add a new product! &raquo;</a> </p>
        <thead z>
          <tr>
           <th><h2>All products</h2></th>
         </tr>
       </thead>

       <% @products.each do |product| %>
       <a href="/admin_products/<%= product.id %>">
      <thead class="thead-inverse">
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Photo</th>
          <th>Show</th>
          <th>Edit</th>
          <th>Destroy</th>
        </tr>
       </thead>
      <tbody>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= product.photo %></td>
          <td><%= link_to 'Show', admin_product_path(product),
            :class => "btn btn-primary"%></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product),
            :class => "btn btn-warning"%></td>
          <td><%= link_to 'Destroy', admin_product_path(product),
              confirm: 'Are you sure?',
              method: :delete,
              :class => "btn btn-danger"%></td>
        </tr>
      </tbody>
      <% end %>
    </table>
    </div>
  </div>