config/routes.rb
Rails.application.routes.draw do

  # PUBLIC ROUTES

  mount Attachinary::Engine => "/attachinary"

   root to: 'pages#home'

   # get '/instahome' => 'pages#instahome'
  # gem high voltage to use a helper method for static pages

  get '/contact' => 'pages#contact'

  get '/home' => 'pages#home'

  get '/about' => 'pages#about'
  get '/press' => 'pages#press'

  get '/collection' => 'products#index'


  resources :products, only: [:show]

  resources :scenes, only: [:show]

  # ADMIN ROUTES


  get '/admin' => 'admin/dashboards#show' # I added this route because I kept typing it.

  devise_for :users

  namespace :admin do

    resources :scenes do
      member do
        delete :remove_product
        post :add_product
      end
    end

    resources :products
    resource :dashboard, only: [:show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :products, dependent: :nullify
  has_attachment :banner

  scope :last_2, -> { order(created_at: :desc).first(2) }

  validates :title, presence: true
  validates :description, presence: true

end

app/controllers/admin/scenes_controller.rb
module Admin
  class ScenesController < BaseController
  layout 'admin'
  before_action :authenticate_user!
  before_action :set_scene, only: [:show, :edit, :update, :destroy, :add_product]
  before_action :set_product, only: [:add_product]
    def new
      @scene = Scene.new
    end

    def create
     scene = Scene.new(scene_params)
      if scene.save
        redirect_to admin_scene_path(scene)
      else
        render :new
      end
    end

    def index
      @scenes = Scene.all
    end

    def show
      @products = Product.all - @scene.products
    end

    def edit
    end

    def update
      @scene.update(scene_params)
      redirect_to admin_scene_path(@scene)
    end

    def add_product
      @product.scene = @scene
      if @product.save
        redirect_to admin_scene_path(@scene)
      else
        @products = Product.all - @scene.products
        render :show
      end
    end

    def remove_product
      product = Product.find(params[:id])
      scene = product.scene
      product.scene_id = nil
      if product.save
        redirect_to admin_scene_path(scene)
        flash[:notice] = product.name + " removed!"
      end
    end

    def destroy
      @scene.destroy
      redirect_to admin_scenes_path
    end

  private

    def set_scene
      @scene = Scene.find(params[:id])
    end

    def set_product
      @product = Product.find(params.require(:scene).fetch(:products))
    end


    def scene_params
      params.require(:scene).permit(:title, :description, :banner)
    end

  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController

  def show
    @scene = Scene.find(params[:id])

    # SCENE SHOW PAGE SLIDING

    # TODO cl image path stuff

    array_all_id = Scene.all.pluck(:id)
    current_id = @scene.id
    index_current_id = array_all_id.index(current_id)

    next_id = array_all_id[index_current_id + 1]
    previous_id = array_all_id[index_current_id - 1]

    # ROTATION LOGIC

    case current_id
    when array_all_id.last
      next_id = array_all_id.first
    when array_all_id.first
      previous_id = array_all_id.last
    end

    @next_scene = Scene.find(next_id)
    @previous_scene = Scene.find(previous_id)
  end

end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/index.html.erb
<h1 hidden>Moussaillon | Furniture | Oak Table | Marble | Steel</h1>
<div id="page-wrapper">
  <div class="container-fluid">
    <% @products.each do |product| %>
      <%= product.name %>
      <%= product.description %>
    <% end %>
  </div>
</div>

app/views/scenes/show.html.erb
<h1 hidden>Moussaillon | Furniture | Oak Table | Marble | Steel</h1>
<section class="banner-show" id="scene-banner-display">
  <div class="scene-banner" style="background-image: url('<%= cl_image_path @scene.banner.path %>'); background-size: 100%; background-repeat: no-repeat;">
  </div>

  <div class="button-positioner">
    <%= link_to "", scene_path(@previous_scene), class: "fa fa-angle-left fa-2x previous-button rotation-button", rel: "nofollow", target: "_blank" %>
    <%= link_to "", scene_path(@next_scene), class: "fa fa-angle-right fa-2x  next-button rotation-button", rel: "nofollow", target: "_blank" %>
  </div>
</section>
<!-- Popular Products -->
<section class="padding-top-50 padding-bottom-100" id="diminished-padding-response">
  <div class="container">
   <div id="description-title text-center">
    <p> <em> <%= @scene.description %> </em> <br>
    </p>
  </div>
  <!--======= PRODUCT DESCRIPTION =========-->
  <div class="item-decribe">
    <!-- Nav tabs -->
    <ul class="nav nav-tabs">
      <li class="active"><a href="#tags">PRODUCTS</a></li>
    </ul>
  </div>


  <!-- Tab panes -->
  <div class="tab-content animate fadeInUp" data-wow-delay="0.4s">
    <!-- DESCRIPTION -->
    <!-- TAGS -->
    <div role="tabpanel" class="tab-pane fade in active" id="tags">

      <div class="container">
        <!-- Popular Item Slide -->
        <div class="shop-items row">

          <% @scene.products.each do |product| %>

          <!-- Item -->
          <div class="col-xs-12 col-sm-6">
            <div class="item">
              <!-- Item Name -->
              <div class="item-name"> <a href="#."><%= product.name %></a>
<!--                 <p><%#= product.description %></p>
                <p> Added on <%#= product.created_at.strftime("%A, %b %d") %></p> -->
              </div>
              <!-- Item img -->
              <%= link_to product_path(product), rel: "nofollow", target: "_blank" do %>
              <div class="item-img">
                <img class="img-1" src=<%= cl_image_path product.photos.first.path unless product.photos.blank? %> style="width: 100%;" alt="">
                <div class="inn">
                  <a href="<%= product_path(product) %>"> Show <a href="#.">
                  </a>
                </div>
              </div>
              <% end %>
              <!-- Price -->
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>