config/routes.rb
Rails.application.routes.draw do

  # PUBLIC ROUTES

  mount Attachinary::Engine => "/attachinary"

   root to: 'pages#home'

   # get '/instahome' => 'pages#instahome'
  # gem high voltage to use a helper method for static pages

  get '/contact' => 'pages#contact'

  get '/home' => 'pages#home'

  get '/about' => 'pages#about'
  get '/press' => 'pages#press'

  get '/collection' => 'products#index'


  resources :products, only: [:show]

  resources :scenes, only: [:show]

  # ADMIN ROUTES


  get '/admin' => 'admin/dashboards#show' # I added this route because I kept typing it.

  devise_for :users

  namespace :admin do

    resources :scenes do
      member do
        delete :remove_product
        post :add_product
      end
    end

    resources :products
    resource :dashboard, only: [:show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scene.rb
class Scene < ApplicationRecord
  has_many :products, dependent: :nullify
  has_attachment :banner

  scope :last_2, -> { order(created_at: :desc).first(2) }

  validates :title, presence: true
  validates :description, presence: true

end

app/controllers/admin/scenes_controller.rb
module Admin
  class ScenesController < BaseController
  layout 'admin'
  before_action :authenticate_user!
  before_action :set_scene, only: [:show, :edit, :update, :destroy, :add_product]
  before_action :set_product, only: [:add_product]
    def new
      @scene = Scene.new
    end

    def create
     scene = Scene.new(scene_params)
      if scene.save
        redirect_to admin_scene_path(scene)
      else
        render :new
      end
    end

    def index
      @scenes = Scene.all
    end

    def show
      @products = Product.all - @scene.products
    end

    def edit
    end

    def update
      @scene.update(scene_params)
      redirect_to admin_scene_path(@scene)
    end

    def add_product
      @product.scene = @scene
      if @product.save
        redirect_to admin_scene_path(@scene)
      else
        @products = Product.all - @scene.products
        render :show
      end
    end

    def remove_product
      product = Product.find(params[:id])
      scene = product.scene
      product.scene_id = nil
      if product.save
        redirect_to admin_scene_path(scene)
        flash[:notice] = product.name + " removed!"
      end
    end

    def destroy
      @scene.destroy
      redirect_to admin_scenes_path
    end

  private

    def set_scene
      @scene = Scene.find(params[:id])
    end

    def set_product
      @product = Product.find(params.require(:scene).fetch(:products))
    end


    def scene_params
      params.require(:scene).permit(:title, :description, :banner)
    end

  end
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController

  def show
    @scene = Scene.find(params[:id])

    # SCENE SHOW PAGE SLIDING

    # TODO cl image path stuff

    array_all_id = Scene.all.pluck(:id)
    current_id = @scene.id
    index_current_id = array_all_id.index(current_id)

    next_id = array_all_id[index_current_id + 1]
    previous_id = array_all_id[index_current_id - 1]

    # ROTATION LOGIC

    case current_id
    when array_all_id.last
      next_id = array_all_id.first
    when array_all_id.first
      previous_id = array_all_id.last
    end

    @next_scene = Scene.find(next_id)
    @previous_scene = Scene.find(previous_id)
  end

end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/admin/scenes/edit.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
     <div class= "col-xs-12 col-sm-6 col-sm-offset-3">
       <h1>Edit Scene</h1>
       <%= simple_form_for @scene, :url => url_for(:action => 'update', :controller => 'scenes'), :method => :patch,  html: {class: 'form-horizontal'} do |f| %>
       <%= f.input :title, :input_html => {class: "form-control", placeholder: "Name" }, label: false %>
       <br>
       <%= f.input :description, :input_html => {class: "form-control", placeholder: "Description" }, label: false %>
       <br>
       <%= f.input :banner, as: :attachinary, :input_html => { class: "form-control-file" } %>
       <br>
       <%= f.submit class: "btn btn-primary" %>
       <% end %>
     </div>
   </div>
 </div>
</div>

app/views/admin/scenes/index.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->

    <!-- /#page-wrapper -->

    <div class="jumbotron">
      <table class="table table-striped table-hover">
        <p><a href="/admin/scenes/new" class="btn btn-primary" role="button"> Add a new scene! &raquo;</a> </p>
        <thead z>
          <tr>
           <th><h2>All Scenes</h2></th>
         </tr>
       </thead>

       <% @scenes.each do |scene| %>
       <a href="/admin_scenes/<%= scene.id %>">
        <thead class="thead-inverse">
          <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Show</th>
            <th>Edit</th>
            <th>Destroy</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= scene.title %></td>
            <td><%= scene.description %></td>
            <td><%= link_to 'Show', admin_scene_path(scene),
              :class => "btn btn-primary", rel: "nofollow", target: "_blank"%></td>
              <td><%= link_to 'Edit', edit_admin_scene_path(scene),
                :class => "btn btn-warning", rel: "nofollow", target: "_blank"%></td>
                <td><%= link_to 'Destroy', admin_scene_path(scene),
                  confirm: 'Are you sure?',
                  method: :delete,
                  :class => "btn btn-danger", rel: "nofollow", target: "_blank"%></td>
                </tr>
              </tbody>
              <% end %>
            </table>
          </div>

app/views/admin/scenes/new.html.erb
<!-- app/views/products/_form.html.erb -->

<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          Add a scene
        </h1>
        <ol class="breadcrumb">
          <li>
            <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
          </li>
          <li class="active">
            <i class="fa fa-desktop"></i> Scenes
          </li>
          <li>
            <i class="fa fa-desktop"></i> New
          </li>
        </ol>
      </div>
    </div>
    <!-- /.row -->
<!-- TODO: ADD PHOTO UPLOADER FOR BANNER, SO WALKTHROUGH ADDING CARRIERWAVE GEM TO SCENE MODEL -->
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <h1>Add Scene</h1>
      <%= simple_form_for @scene, :url => url_for(action: 'create', controller: 'scenes'), :method => :post,  html: {class: 'form-horizontal'} do |f| %>
      <%= f.input :title, :input_html => {class: "form-control", placeholder: "Name" }, label: false %>
      <br>
      <%= f.input :description, :input_html => {class: "form-control", placeholder: "Description" }, label: false %>
      <br>
      <%= f.input :banner, as: :attachinary, :input_html => { class: "form-control-file" } %>

      <br>
      <%= f.submit class: "btn btn-primary" %>
      <% end %>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/admin/scenes/show.html.erb
<div id="page-wrapper">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12">
         <% if @scene.banner? %>
          <%= cl_image_tag @scene.banner.path, width: 1000, height: 400, crop: :fill %>
          <% end %>
         <h1 class="page-header">
          <%= @scene.title %>
          <%= @scene.description %>
        </h1>
      </div>
    </div>
  <div class="row">
    <div class="col-sm-6 col-xs-12">
       <% @scene.products.each do |product|%>
      <div class="col-xs-6 pull-left">
       <h2><%= product.name %></h2>
       <p><%= product.price %>€</p>
       <p><%= product.description %></p>
         <div class="buttons" style="display: flex;">
           <%= button_to "Remove product", remove_product_admin_scene_path(product), class: 'btn btn-danger', method: :delete, data: {confirm: "Are you sure?"} %>
           <%= link_to "Show", admin_product_path(product), class: 'btn btn-primary', rel: "nofollow", target: "_blank" %>
         </div>
      </div>
       <%end%>
      </div>
      <div class="col-sm-6 text-center ">
      <h4>
        Add a new product
      </h4>
        <%= simple_form_for @scene, :url => add_product_admin_scene_path, :method => :post,  html: {class: 'form-horizontal'} do |f| %>
          <%= f.input :products, collection: @products, label: false, input_html: { class: 'dropdown-form-scene-show'}  %>
          <%= f.submit 'Add Product', class: "btn btn-primary"%>
        <% end %>
      </div>
    </div>
  </div>
</div>