config/routes.rb
Rails.application.routes.draw do

  # PUBLIC ROUTES

  mount Attachinary::Engine => "/attachinary"

   root to: 'pages#home'

   # get '/instahome' => 'pages#instahome'
  # gem high voltage to use a helper method for static pages

  get '/contact' => 'pages#contact'

  get '/home' => 'pages#home'

  get '/about' => 'pages#about'
  get '/press' => 'pages#press'

  get '/collection' => 'products#index'


  resources :products, only: [:show]

  resources :scenes, only: [:show]

  # ADMIN ROUTES


  get '/admin' => 'admin/dashboards#show' # I added this route because I kept typing it.

  devise_for :users

  namespace :admin do

    resources :scenes do
      member do
        delete :remove_product
        post :add_product
      end
    end

    resources :products
    resource :dashboard, only: [:show]

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  CATEGORIES = ["eat", "sleep", "live", "sit", "cook"].freeze
  belongs_to :scene, optional: true

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_attachments :photos, maximum: 5
  include PgSearch
  pg_search_scope :search_name_and_description, against: [:name, :description, :category], using: {tsearch: {prefix: true, dictionary: "english"}}
  pg_search_scope :find_by_category, against: [:category]


  validates :name, presence: true
  validates :description, presence: true
  # validates :price, presence: true
  validates :category, presence: true, inclusion: CATEGORIES

end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < ApplicationController
    layout 'admin'
    before_action :authenticate_user!
    before_action :set_product, only: [:show, :edit, :update, :destroy]

    def new
      @product = Product.new
    end

    def create
     @product = Product.new(product_params)
      if @product.save
        redirect_to admin_product_path(@product)
      else
        render :new
      end
    end

    def index
      @products = Product.all
    end

    def show
      # @product = Product.find(params[:id])
    end

    def edit
      # @product = Product.find(params[:id])
    end

    def update
      # @product = product.find(params[:id])
      @product.update(product_params)
      redirect_to admin_product_path(@product)
    end

    def destroy
      # @product = Product.find(params[:id])
      @product.destroy
      redirect_to admin_products_path
    end

    private

    def set_product
      @product = Product.friendly.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :category, :designer, :material, photos: [])
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.friendly.find(params[:id])
  end

# was thinking instead of making a shop / index / result page, just do an index one and set the products based on the params. What do you think?

  def index
    @query = params[:type] || 'all'
    if query = params[:search]
      @query = query
      @products = Product.search_name_and_description(query)
      @info_title = "Results for #{query}"
    elsif type = params[:type]
      @products = Product.find_by_category(type)
      @products.count > 1
      @info_title = type
    else
      @products = Product.all
      @info_title = nil
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_contact-modal.html.erb
<div class="modal fade" id="modal-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">I LOVE IT</h4>
      </div>
      <div class="modal-body">
        <form role="form" id="contact_form" class="contact-form" method="post" action="https://formspree.io/f/mlezrolw">
          <ul class="row">
            <li class="col-sm-6">
              <label>full name *
                <input type="text" class="form-control" name="name" id="name">
              </label>
            </li>
            <li class="col-sm-6">
              <label>Email *
                <input type="text" class="form-control" name="email" id="email" placeholder="">
              </label>
            </li>
            <li class="col-sm-6">
              <label>Phone *
                <input type="text" class="form-control" name="company" id="company" placeholder="">
              </label>
            </li>
            <li class="col-sm-6">
              <label>SUBJECT
                <input type="text" class="form-control" name="website" id="website" placeholder="" value="<%= @product.name %>">
              </label>
            </li>
            <li class="col-sm-12">
              <label>Message
                <textarea class="form-control" name="message" id="message" rows="5">I am super interested in <%= @product.name %>! Can you get back to me with some more information?</textarea>
              </label>
            </li>
            <li class="col-sm-12">
              <button type="submit" value="submit" class="btn" id="btn_submit" onClick="proceed();">SEND MAIL</button>
            </li>
          </ul>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/products/admin_show.html.erb
<div id="page-wrapper">

  <div class="container-fluid">

    <!-- Page Heading -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">
          <%= @product.name %>
          <small><%= @product.description %></small>
        </h1>
        <ol class="breadcrumb">
          <li>
            <i class="fa fa-dashboard"></i>  <a href="index.html">Dashboard</a>
          </li>
          <li class="active">
            <i class="fa fa-file"></i> Blank Page
          </li>
        </ol>
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container-fluid -->

</div>
<!-- /#page-wrapper -->

app/views/products/index.html.erb
<h1 hidden>Moussaillon | Furniture | Oak Table | Marble | Steel</h1>

<div class="side-bar-nav">
  <%= link_to 'All', collection_path, rel: "nofollow", target: "_blank" id: 'all' %>
  <%= link_to 'Sleep', collection_path(type: "sleep"), rel: "nofollow", target: "_blank" id: 'sleep' %>
  <%= link_to 'Eat', collection_path(type: "eat"), rel: "nofollow", target: "_blank" id: 'eat' %>
  <%= link_to 'Live', collection_path(type: "live" ), rel: "nofollow", target: "_blank" id: 'live' %>
  <%= link_to 'Cook', collection_path(type: "cook" ), rel: "nofollow", target: "_blank" id: 'cook' %>
  <%= link_to 'Sit', collection_path(type: "sit" ), rel: "nofollow", target: "_blank" id: 'sit' %>
</div>
 <!-- Popular Products -->
 <section id="shop-page" class="shop-page padding-top-50 padding-bottom-200" style="padding-right: 80px">
  <div class="container">
    <div class="item-display">
      <div class="row">
        <div class="col-xs-12">
          <div class="text-center" style="margin-left: 40px;">
            <h2>
            <%= @info_title %>
            </h2>
          </div>
        </div>
        <div class="col-xs-6">
          <span class="product-num">
            Showing 1 - of <%= @products.count %> products
          </span>
        </div>

        <!-- Products Select -->
      </div>

      <!-- Popular Item Slide -->

      <ul class="row">
        <div class="shop-items row">

          <% @products.each do |product| %>

          <!-- Item -->
          <div class="col-xs-12 col-sm-6">
            <div class="item">
              <!-- Item Name -->
              <div class="item-name"> <a href="#."><%= product.name %></a>
<!--                 <p><%#= product.description %></p>
                <p> Added on <%#= product.created_at.strftime("%A, %b %d") %></p> -->
              </div>
              <!-- Item img -->
              <%= link_to product_path(product), rel: "nofollow", target: "_blank" do %>
              <div class="item-img">
                <img class="img-1" src=<%= cl_image_path product.photos.first.path unless product.photos.blank? %> alt="moussaillon" style="width: 100%; max-height: 700px;">
                <div class="inn">
                  <a href="<%= product_path(product) %>"> Show <a href="#.">
                  </a>
                </div>
              </div>
              <% end %>
              <!-- Price -->
            </div>
          </div>
          <% end %>

          </div>
        </ul>
    </div>
  </div>
</section>


<% content_for(:after_js) do %>
  <script>
    $("#<%= @query %>").addClass('nav-active');
  </script>
<% end %>

app/views/products/show.html.erb
<%= render 'contact-modal' %>

<div class="content">

    <!-- Popular Products -->
    <section class="padding-top-100 padding-bottom-100">
      <div class="container">

        <!-- SHOP DETAIL -->
        <div class="shop-detail">
          <div class="row">

            <!-- Popular Images Slider -->
            <div class="col-md-7">
              <!-- Images Slider -->
              <div class="images-slider">
                <ul class="slides">
                  <% @product.photos.each do |photo| %>
                  <li data-thumb="<%= cl_image_path photo.path %>"> <img class="img-responsive" src="<%= cl_image_path photo.path %>"  alt=""> </li>
                  <% end %>
                </ul>
              </div>
            </div>

            <!-- COntent -->
            <div class="col-md-5">
              <h4><%= @product.name %></h4>

              <!-- Sale Tags -->
              <ul class="item-owner">
                <li>Designer :<span> <%= @product.designer.try(:capitalize) %></span></li>
                <li>Material:<span> <%= @product.material.try(:capitalize) %></span></li>
                <!-- <li>Price:<span> € <%#= @product.price %> </span></li> -->
              </ul>

              <!-- Item Detail -->
              <p><%= @product.description %></p>

              <!-- Short By -->
              <div class="some-info">
                <ul class="row margin-top-30">
                  <li class="col-xs-6"> <button data-toggle="modal" data-target="#modal-1" class="btn">GET IN TOUCH</button> </li>
                </ul>

                <!-- INFOMATION -->
                <div class="inner-info">
                  <h6>DELIVERY INFORMATION</h6>
                  <p> We deliver worldwide. Leave your address in your request and we will answer with delivery details. </p>
              <!--     <h6>SHIPPING & RETURNS</h6> -->
                  <h6>SHARE THIS PRODUCT</h6>
                  <!-- Social Icons -->
                  <ul class="social_icons">
                    <li> <a href="#." class="like-us" data-toggle="modal" data-target="#modal-1"><i class="fa fa-pinterest"></i></a> </li>
                    <li><a href="https://www.facebook.com/moussaillonfurniture"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="https://www.instagram.com/moussaillonmaker/"><i class="fa fa-instagram"></i></a></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!--======= PRODUCT DESCRIPTION =========-->
<!--         <div class="item-decribe">
          <ul class="nav nav-tabs animate fadeInUp" data-wow-delay="0.4s" role="tablist">
            <li role="presentation" class="active"><a href="#descr" role="tab" data-toggle="tab">DESCRIPTION</a></li>
          </ul>

          <div class="tab-content animate fadeInUp" data-wow-delay="0.4s">
            <div role="tabpanel" class="tab-pane fade in active" id="descr">
              <h3><%#= @product.description %> </h3>

            </div>

            <div role="tabpanel" class="tab-pane fade" id="tags"> </div>
          </div>
        </div> -->
      </div>
    </section>

    <!-- Popular Products -->
</div>